var _ = require('underscore');
var assert = require('chai').assert;
var nock = require('nock');

var client = require('../lib/leetcode_client');
var config = require('../lib/config');
var core = require('../lib/core');

describe('leetcode_client', function() {
  before(function() {
    config.init();
  });

  describe('#autologin', function() {
    var _core;

    before(function() {
      config.AUTO_LOGIN = true;
      _core = _.clone(core);

      core.getUser = function() {
        return {};
      };
      core.login = function(user, cb) {
        return cb(null, user);
      };
    });

    // restore to original 'core'
    after(function() {
      _.extendOwn(core, _core);
    });

    it('should ok', function(done) {
      nock(config.URL_PROBLEMS).get('/').reply(403);
      nock(config.URL_PROBLEMS).get('/').replyWithFile(200, './test/mock/problems.json.20160911');

      client.getProblems(function(e, problems) {
        assert.equal(e, null);
        assert.equal(problems.length, 377);

        done();
      });
    });
  });

  describe('#getProblems', function() {
    it('should ok', function(done) {
      nock(config.URL_PROBLEMS)
        .get('/')
        .replyWithFile(200, './test/mock/problems.json.20160911');

      client.getProblems(function(e, problems) {
        assert.equal(e, null);
        assert.equal(problems.length, 377);

        done();
      });
    });
  }); // #getProblems

  describe('#getProblem', function() {
    it('should ok', function(done) {
      var problem = {
        id:     389,
        name:   'Find the Difference',
        key:    'find-the-difference',
        link:   'https://leetcode.com/problems/find-the-difference',
        locked: false
      };

      nock('https://leetcode.com')
        .get('/problems/find-the-difference')
        .replyWithFile(200, './test/mock/find-the-difference.html.20160911');

      client.getProblem(problem, function(e, problem) {
        assert.equal(e, null);
        assert.equal(problem.totalAC, 15674);
        assert.equal(problem.totalSubmit, 32141);
        assert.equal(problem.desc,
          [
            '',
            'Given two strings s and t which consist of only lowercase letters.',
            '',
            'String t is generated by random shuffling string s and then add one more letter at a random position.',
            '',
            'Find the letter that was added in t.',
            '',
            'Example:',
            '',
            'Input:',
            's = "abcd"',
            't = "abcde"',
            '',
            'Output:',
            'e',
            '',
            'Explanation:',
            "'e' is the letter that was added.",
            ''
          ].join('\r\n'));

        assert.equal(problem.templates.length, 7);

        assert.equal(problem.templates[0].value, 'cpp');
        assert.equal(problem.templates[0].text, 'C++');
        assert.equal(problem.templates[0].defaultCode,
          [
            'class Solution {',
            'public:',
            '    char findTheDifference(string s, string t) {',
            '        ',
            '    }',
            '};'
          ].join('\r\n'));

        assert.equal(problem.templates[1].value, 'java');
        assert.equal(problem.templates[1].text, 'Java');
        assert.equal(problem.templates[1].defaultCode,
          [
            'public class Solution {',
            '    public char findTheDifference(String s, String t) {',
            '        ',
            '    }',
            '}'
          ].join('\r\n'));

        assert.equal(problem.templates[2].value, 'python');
        assert.equal(problem.templates[2].text, 'Python');
        assert.equal(problem.templates[2].defaultCode,
          [
            'class Solution(object):',
            '    def findTheDifference(self, s, t):',
            '        """',
            '        :type s: str',
            '        :type t: str',
            '        :rtype: str',
            '        """'
          ].join('\r\n'));

        assert.equal(problem.templates[3].value, 'c');
        assert.equal(problem.templates[3].text, 'C');
        assert.equal(problem.templates[3].defaultCode,
          [
            'char findTheDifference(char* s, char* t) {',
            '    ',
            '}'
          ].join('\r\n'));

        assert.equal(problem.templates[4].value, 'csharp');
        assert.equal(problem.templates[4].text, 'C#');
        assert.equal(problem.templates[4].defaultCode,
          [
            'public class Solution {',
            '    public char FindTheDifference(string s, string t) {',
            '        ',
            '    }',
            '}'
          ].join('\r\n'));

        assert.equal(problem.templates[5].value, 'javascript');
        assert.equal(problem.templates[5].text, 'JavaScript');
        assert.equal(problem.templates[5].defaultCode,
          [
            '/**',
            ' * @param {string} s',
            ' * @param {string} t',
            ' * @return {character}',
            ' */',
            'var findTheDifference = function(s, t) {',
            '    ',
            '};'
          ].join('\r\n'));

        assert.equal(problem.templates[6].value, 'ruby');
        assert.equal(problem.templates[6].text, 'Ruby');
        assert.equal(problem.templates[6].defaultCode,
          [
            '# @param {String} s',
            '# @param {String} t',
            '# @return {Character}',
            'def find_the_difference(s, t)',
            '    ',
            'end'
          ].join('\r\n'));

        done();
      });
    });
  }); // #getProblem

  describe('#testProblem', function() {
    it('should ok', function(done) {
      var problem = {
        id:     389,
        name:   'Find the Difference',
        key:    'find-the-difference',
        link:   'https://leetcode.com/problems/find-the-difference',
        locked: false,
        file:   '/dev/null'
      };

      nock('https://leetcode.com')
        .post('/problems/find-the-difference/interpret_solution/')
        .reply(200, '{"interpret_expected_id": "id1", "interpret_id": "id2"}');

      nock('https://leetcode.com')
        .get('/submissions/detail/id1/check/')
        .reply(200, '{"state": "SUCCESS"}');

      nock('https://leetcode.com')
        .get('/submissions/detail/id2/check/')
        .reply(200, '{"state": "SUCCESS"}');

      client.testProblem(problem, function(e, results) {
        assert.equal(e, null);
        assert.deepEqual(results,
          [
            {name: 'Your', state: 'SUCCESS'},
            {name: 'Expected', state: 'SUCCESS'}
          ]);

        done();
      });
    });
  }); // #testProblem

  describe('#submitProblem', function() {
    it('should ok', function(done) {
      var problem = {
        id:     389,
        name:   'Find the Difference',
        key:    'find-the-difference',
        link:   'https://leetcode.com/problems/find-the-difference',
        locked: false,
        file:   '/dev/null'
      };

      nock('https://leetcode.com')
        .post('/problems/find-the-difference/submit/')
        .reply(200, '{"submission_id": "id1"}');

      nock('https://leetcode.com')
        .get('/submissions/detail/id1/check/')
        .reply(200, '{"state": "SUCCESS"}');

      client.submitProblem(problem, function(e, results) {
        assert.equal(e, null);
        assert.deepEqual(results, [{name: 'Your', state: 'SUCCESS'}]);

        done();
      });
    });
  }); // #submitProblem

  describe('#starProblem', function() {
    it('should ok', function(done) {
      var problem = {
        id:     389,
        name:   'Find the Difference',
        key:    'find-the-difference',
        link:   'https://leetcode.com/problems/find-the-difference',
        locked: false,
        file:   '/dev/null'
      };

      nock('https://leetcode.com')
        .post('/problems/favor/')
        .reply(200, '{"is_favor": true}');

      client.starProblem(problem, true, function(e, starred) {
        assert.equal(e, null);
        assert.equal(starred, true);
        done();
      });
    });
  }); // #starProblem

  describe('#getSubmissions', function() {
    it('should ok', function(done) {
      var problem = {
        id:     1,
        name:   'Two Sum',
        key:    'two-sum',
        link:   'https://leetcode.com/problems/two-sum',
        locked: false
      };

      nock('https://leetcode.com')
        .get('/problems/two-sum/submissions/')
        .replyWithFile(200, './test/mock/two-sum.submissions.html.20161006');

      client.getSubmissions(problem, function(e, submissions) {
        assert.equal(e, null);

        assert.equal(submissions.length, 2);

        assert.deepEqual(submissions[0], {
          id:      '73790064',
          lang:    'cpp',
          runtime: '9 ms',
          path:    '/submissions/detail/73790064/',
          state:   'Accepted'
        });

        assert.deepEqual(submissions[1], {
          id:      '73489296',
          lang:    'cpp',
          runtime: 'N/A',
          path:    '/submissions/detail/73489296/',
          state:   'Wrong Answer'
        });

        done();
      });
    });
  }); // #getSubmissions

  describe('#getSubmission', function() {
    it('should ok', function(done) {
      var submission = {
        id:      '73790064',
        lang:    'cpp',
        runtime: '9 ms',
        path:    '/submissions/detail/73790064/',
        state:   'Accepted'
      };

      nock('https://leetcode.com')
        .get('/submissions/detail/73790064/')
        .replyWithFile(200, './test/mock/two-sum.submission.73790064.html.20161006');

      client.getSubmission(submission, function(e, submission) {
        assert.equal(e, null);

        assert.deepEqual(submission.code,
          [
            'class Solution {',
            'public:',
            '    vector<int> twoSum(vector<int>& nums, int target) {',
            '        return res;',
            '    }',
            '};',
            ''
          ].join('\r\n'));

        done();
      });
    });
  }); // #getSubmission

  describe('#login', function() {
    it('should ok', function(done) {
      nock(config.URL_LOGIN).get('/').reply(200, '', {
        'Set-Cookie': [
          'csrftoken=LOGIN_CSRF_TOKEN; Max-Age=31449600; Path=/; secure'
        ]
      });

      nock(config.URL_LOGIN).post('/').reply(302, '', {
        'Set-Cookie': [
          'csrftoken=SESSION_CSRF_TOKEN; Max-Age=31449600; Path=/; secure',
          'PHPSESSID=SESSION_ID; Max-Age=31449600; Path=/; secure',
          "messages='Successfully signed in as Eric.'; Max-Age=31449600; Path=/; secure"
        ]
      });

      var user = {};
      client.login(user, function(e, user) {
        assert.equal(e, null);

        assert.equal(user.loginCSRF, 'LOGIN_CSRF_TOKEN');
        assert.equal(user.sessionCSRF, 'SESSION_CSRF_TOKEN');
        assert.equal(user.sessionId, 'SESSION_ID');
        assert.equal(user.name, 'Eric');

        done();
      });
    });
  }); // #login
});
