#!/bin/sh

srcdir=/root/leetcode-cli
leetcode=$srcdir/bin/leetcode

if [ ! -f "$leetcode" ]; then
  echo "Not found leetcode, install now ..."
  mkdir -p $srcdir
  tar zxf /leetcode-cli.tar.gz -C $srcdir
fi

export TERM=xterm-256color
exec $leetcode $@
